# This file controls the AWS CodeBuild

version: 0.2
phases:
  pre_build:
    commands:
    - echo "Entered the pre-build phase"
  build:
    commands:
    - echo "Entered build phase"
    - mvn clean package -DskipTests -P cloud
  post_build:
    commands:
    - echo "Build en suuces"
artifacts:
  files:
    - target/my-reviews.jar
  discard-paths: yes